[package]
name = "search-word"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
"csv" = { path = "csv" }
"word_distance" = { path = "word_distance" }
wasm-bindgen = "0.2.95"
